name: Docker build and push template
on:
  push:
    branches:
      - resolve-approots
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: write
jobs:
  build-php-8_2-core:
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.2-base-ai
      drupal_version: '10.4.x'
      image_tag_suffix: core
    secrets: inherit

  build-php-8_3-cms:
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.3-base-ai
      image_tag_suffix: cms
    secrets: inherit

  build-php-8_3-core:
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.3-base-ai
      image_tag_suffix: core
    secrets: inherit
