# Jobs require one another to prevent time-outs.
name: Docker build and push template
on:
  push:
    branches:
      - 1.0.x
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  actions: write
jobs:
  build-php-8_2-core:
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.2-base-ai
      drupal_core_version: '10.x'
      image_tag_suffix: core
    secrets: inherit

  build-php-8_3-cms:
    needs: build-php-8_2-core
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.3-base-ai
      drupal_version: '1.2.0'
      image_tag_suffix: cms
    secrets: inherit

  build-php-8_3-core:
    needs: build-php-8_3-cms
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      webserver_image: devpanel/php:8.3-base-ai
      drupal_core_version: '11.x'
      image_tag_suffix: core
    secrets: inherit
